### PR TITLE
Create RefundList.cs

### PR DESCRIPTION
**Pull request by zamap**

### CODE REVIEW

**Comment by zamap** [comment]
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/57
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/59

**Comment by bzaar** [comment]
This PR doesn't seem to make much sense on its own. Can you provide a complete implementation of a feature in one PR?

**Comment by zamap** [comment]
please look into referenced pr https://github.com/morpher-ru/Yandex.Checkout.V3/pull/57
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/59

**Comment by zamap** [comment]
Added missing files  waiting for nuget updated

**Comment by bzaar** [comment]
GetRefunds() has been implemeted already. Sorry for front-running you.

**Pull request closed without merging**
