### PR TITLE
Update GetReceiptsFilter.cs

### PR DESCRIPTION
**Pull request by zamap**
fix AppendDate

### CODE REVIEW

**Comment by zamap** [comment]
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/57
https://github.com/morpher-ru/Yandex.Checkout.V3/pull/58

**Comment by bzaar** [comment]
Thanks for this PR. How was AppendDate() broken?

**Comment by bzaar** [comment]
Aha! I've added a test which highlights the problem: a253c2c6e94678fb526f87c41fc9a8314c11e684 

This code wasn't tested enough.

You PR should fix it. Thanks!

**Comment by bzaar** [comment]
> You PR should fix it.

And indeed it did: [before](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49686310), [after](https://ci.appveyor.com/project/morpher/yandex-checkout-v3/builds/49686328).

**Pull request merged**
